/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalibrationSettings {
  'efficiencyMultiplier' : number,
  'soilingFactor' : number,
  'temperatureCoefficient' : number,
}
export interface Location {
  'latitude' : number,
  'cityName' : string,
  'longitude' : number,
}
export interface NamedPreset { 'timestamp' : Time, 'config' : SystemConfig }
export interface PVArrayConfig {
  'panelCount' : bigint,
  'name' : string,
  'azimuthAngle' : number,
  'enabled' : boolean,
  'panelWattage' : bigint,
  'tiltAngle' : number,
}
export interface SystemConfig {
  'arrays' : Array<PVArrayConfig>,
  'unitPreference' : string,
  'calibration' : CalibrationSettings,
  'co2EmissionFactor' : number,
  'electricityPrice' : number,
  'location' : Location,
  'systemName' : string,
}
export type Time = bigint;
export interface UserPreferences {
  'preferredTab' : string,
  'unitSystem' : string,
}
export interface _SERVICE {
  'getPreferences' : ActorMethod<[], [] | [UserPreferences]>,
  'getPresets' : ActorMethod<[], Array<[string, NamedPreset]>>,
  'getSystemConfig' : ActorMethod<[], [] | [SystemConfig]>,
  'getUserConfig' : ActorMethod<[Principal], [] | [SystemConfig]>,
  'getUserPresets' : ActorMethod<[Principal], Array<[string, NamedPreset]>>,
  'savePreferences' : ActorMethod<[UserPreferences], undefined>,
  'savePreset' : ActorMethod<[string, SystemConfig], undefined>,
  'saveSystemConfig' : ActorMethod<[SystemConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];