/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserPreferences = IDL.Record({
  'preferredTab' : IDL.Text,
  'unitSystem' : IDL.Text,
});
export const Time = IDL.Int;
export const PVArrayConfig = IDL.Record({
  'panelCount' : IDL.Nat,
  'name' : IDL.Text,
  'azimuthAngle' : IDL.Float64,
  'enabled' : IDL.Bool,
  'panelWattage' : IDL.Nat,
  'tiltAngle' : IDL.Float64,
});
export const CalibrationSettings = IDL.Record({
  'efficiencyMultiplier' : IDL.Float64,
  'soilingFactor' : IDL.Float64,
  'temperatureCoefficient' : IDL.Float64,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'cityName' : IDL.Text,
  'longitude' : IDL.Float64,
});
export const SystemConfig = IDL.Record({
  'arrays' : IDL.Vec(PVArrayConfig),
  'unitPreference' : IDL.Text,
  'calibration' : CalibrationSettings,
  'co2EmissionFactor' : IDL.Float64,
  'electricityPrice' : IDL.Float64,
  'location' : Location,
  'systemName' : IDL.Text,
});
export const NamedPreset = IDL.Record({
  'timestamp' : Time,
  'config' : SystemConfig,
});

export const idlService = IDL.Service({
  'getPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
  'getPresets' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, NamedPreset))],
      ['query'],
    ),
  'getSystemConfig' : IDL.Func([], [IDL.Opt(SystemConfig)], ['query']),
  'getUserConfig' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SystemConfig)],
      ['query'],
    ),
  'getUserPresets' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Tuple(IDL.Text, NamedPreset))],
      ['query'],
    ),
  'savePreferences' : IDL.Func([UserPreferences], [], []),
  'savePreset' : IDL.Func([IDL.Text, SystemConfig], [], []),
  'saveSystemConfig' : IDL.Func([SystemConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserPreferences = IDL.Record({
    'preferredTab' : IDL.Text,
    'unitSystem' : IDL.Text,
  });
  const Time = IDL.Int;
  const PVArrayConfig = IDL.Record({
    'panelCount' : IDL.Nat,
    'name' : IDL.Text,
    'azimuthAngle' : IDL.Float64,
    'enabled' : IDL.Bool,
    'panelWattage' : IDL.Nat,
    'tiltAngle' : IDL.Float64,
  });
  const CalibrationSettings = IDL.Record({
    'efficiencyMultiplier' : IDL.Float64,
    'soilingFactor' : IDL.Float64,
    'temperatureCoefficient' : IDL.Float64,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'cityName' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  const SystemConfig = IDL.Record({
    'arrays' : IDL.Vec(PVArrayConfig),
    'unitPreference' : IDL.Text,
    'calibration' : CalibrationSettings,
    'co2EmissionFactor' : IDL.Float64,
    'electricityPrice' : IDL.Float64,
    'location' : Location,
    'systemName' : IDL.Text,
  });
  const NamedPreset = IDL.Record({
    'timestamp' : Time,
    'config' : SystemConfig,
  });
  
  return IDL.Service({
    'getPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
    'getPresets' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, NamedPreset))],
        ['query'],
      ),
    'getSystemConfig' : IDL.Func([], [IDL.Opt(SystemConfig)], ['query']),
    'getUserConfig' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SystemConfig)],
        ['query'],
      ),
    'getUserPresets' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Tuple(IDL.Text, NamedPreset))],
        ['query'],
      ),
    'savePreferences' : IDL.Func([UserPreferences], [], []),
    'savePreset' : IDL.Func([IDL.Text, SystemConfig], [], []),
    'saveSystemConfig' : IDL.Func([SystemConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };