/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PVArrayConfig {
    panelCount: bigint;
    name: string;
    azimuthAngle: number;
    enabled: boolean;
    panelWattage: bigint;
    tiltAngle: number;
}
export interface Location {
    latitude: number;
    cityName: string;
    longitude: number;
}
export interface UserPreferences {
    preferredTab: string;
    unitSystem: string;
}
export type Time = bigint;
export interface NamedPreset {
    timestamp: Time;
    config: SystemConfig;
}
export interface CalibrationSettings {
    efficiencyMultiplier: number;
    soilingFactor: number;
    temperatureCoefficient: number;
}
export interface SystemConfig {
    arrays: Array<PVArrayConfig>;
    unitPreference: string;
    calibration: CalibrationSettings;
    co2EmissionFactor: number;
    electricityPrice: number;
    location: Location;
    systemName: string;
}
export interface backendInterface {
    getPreferences(): Promise<UserPreferences | null>;
    getPresets(): Promise<Array<[string, NamedPreset]>>;
    getSystemConfig(): Promise<SystemConfig | null>;
    getUserConfig(user: Principal): Promise<SystemConfig | null>;
    getUserPresets(user: Principal): Promise<Array<[string, NamedPreset]>>;
    savePreferences(preferences: UserPreferences): Promise<void>;
    savePreset(name: string, config: SystemConfig): Promise<void>;
    saveSystemConfig(config: SystemConfig): Promise<void>;
}
import type { SystemConfig as _SystemConfig, UserPreferences as _UserPreferences } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getPreferences(): Promise<UserPreferences | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreferences();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreferences();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPresets(): Promise<Array<[string, NamedPreset]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresets();
            return result;
        }
    }
    async getSystemConfig(): Promise<SystemConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemConfig();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemConfig();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserConfig(arg0: Principal): Promise<SystemConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserConfig(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserConfig(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPresets(arg0: Principal): Promise<Array<[string, NamedPreset]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPresets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPresets(arg0);
            return result;
        }
    }
    async savePreferences(arg0: UserPreferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePreferences(arg0);
            return result;
        }
    }
    async savePreset(arg0: string, arg1: SystemConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePreset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePreset(arg0, arg1);
            return result;
        }
    }
    async saveSystemConfig(arg0: SystemConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSystemConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSystemConfig(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPreferences]): UserPreferences | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SystemConfig]): SystemConfig | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
